

GET http://127.0.0.1:8000/api/routes/
Content-Type: application/json
###


POST http://127.0.0.1:8000/api/send-otp/
Content-Type: application/json

{"phone_number":"01303206223"}
###


POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{ "phone_number":"01303206223", "otp":"620526", "password" : "4321" }
###


POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{ "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNDE1MjQxNiwiaWF0IjoxNjk4NjAwNDE2LCJqdGkiOiI0OTcxNjg4YzU2ZGM0OTUwOGQ5ZjVlZjgxZTQ5MDFlYiIsInVzZXJfaWQiOiIwMTMwMzIwNjIyMyJ9.fHBhKtuTD32BSiJxMtxDnacVbwtvLYpaMOWk1iBsP4w" }
###

GET http://127.0.0.1:8000/api/get-todos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NjAwNDc2LCJpYXQiOjE2OTg2MDAyNzEsImp0aSI6ImYzNzUyNTFmZTNlNDQwNDRiMDllYTMzNzZjZGRjZGRiIiwidXNlcl9pZCI6IjAxMzAzMjA2MjIzIn0.C8rK3H0hb_reHKnDz_kmJo_EV27is9NoWP7hw81Wtr8
###
