

GET http://127.0.0.1:8000/api/routes/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NTc0MjM4LCJpYXQiOjE2OTg1NzQxNzgsImp0aSI6Ijc2NzZkNzliZjhhYTRlOTg5OTkyYjE1OGZkNTE1MWMxIiwidXNlcl9pZCI6MX0.QlNxGqzC0riB03bqHLTxbszhupSpEUVkRIO5XXf4VB8
###


POST http://127.0.0.1:8000/api/send-otp/
Content-Type: application/json

{"phone_number":"01303206223"}
###


POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{ "phone_number":"01303206223", "otp":"944270", "password" : "1234" }
###


POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{ "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNDEzNzAyNSwiaWF0IjoxNjk4NTg1MDI1LCJqdGkiOiIwOTlhNmU5Mzc3YzQ0ZGUxOGQ0ZGQzMGNhNWU1NzU1MyIsInVzZXJfaWQiOiIwMTMwMzIwNjIyMyJ9.uCy1pYOU7XMc65KtRnFvcVfGBhuhPl5BoKXahiqRhUQ" }
###



GET http://127.0.0.1:8000/api/get-todos/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NTg1MDExLCJpYXQiOjE2OTg1ODQ5NTEsImp0aSI6IjA0ODI3NTlhZWE4ZTRkMGI4MThjYWViOTYwNmIxMzBkIiwidXNlcl9pZCI6IjAxMzAzMjA2MjIzIn0.VehzrtaGP5w-qDyNK_l7f7UsZX9YrLhC3zBa0ro0UqE
###
