# Generated by Django 4.1 on 2023-09-28 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='uid',
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b4e2150-2c3c-4fa5-a456-3a0eb68ed7af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
