# Generated by Django 4.1 on 2023-09-30 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_todo_uid_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6035c595-e59d-403b-aab4-741bc1284f1a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
