# Generated by Django 4.1 on 2023-10-01 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_todo_user_alter_todo_id_alter_tododeadline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0fea635-21cd-492c-be9b-97d896d97d1f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tododeadline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0fea635-21cd-492c-be9b-97d896d97d1f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
