# Generated by Django 4.1 on 2023-10-07 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_todo_id_alter_tododeadline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90ee8179-d74e-427e-a01a-be13c7460110'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tododeadline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90ee8179-d74e-427e-a01a-be13c7460110'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
