# Generated by Django 4.1 on 2023-10-07 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_todo_id_alter_tododeadline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4d8a45d-63b4-4e9b-8902-781485942ec3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tododeadline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4d8a45d-63b4-4e9b-8902-781485942ec3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
