# Generated by Django 4.2.1 on 2023-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0002_recipe_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['total_view']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['stepId']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
