# Generated by Django 4.2.1 on 2023-06-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
    ]
